spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME}:${POSTGRESQL_PORT}/${POSTGRESQL_DB_NAME}
    username: ${POSTGRESQL_DB_USER}
    password: ${POSTGRESQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

apiServerUrl: https://test-api.novastack.org