server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: ${apiTitle}
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    enabled: true
    path: /api/docs/index.html
    operationsSorter: method
    syntaxHighlight:
      theme: obsidian
    disable-swagger-default-url: true
    supported-submit-methods: []

apiTitle: ${SYS_API_TITLE}
apiDescription: ${SYS_API_DESCRIPTION}
apiVersion: "0.3.0"
apiContactName: ${SYS_API_CONTACT_NAME}
apiContactEmail: ${SYS_API_CONTACT_EMAIL}
apiContactUrl: ${SYS_API_CONTACT_URL}
nodeHostname: ${SYS_NODE_HOSTNAME}