### get all hashtags
GET http://localhost:3000/api/v1/hashtags
Accept: application/json

### get latest hashtags
GET http://localhost:3000/api/v1/hashtags/latest
Accept: application/json

### get the trending hashtags
GET http://localhost:3000/api/v1/hashtags/trending
Accept: application/json

### get a specific hashtag by id
GET http://localhost:3000/api/v1/hashtags/{id}
Accept: application/json