### get all encrypted posts
GET http://localhost:3000/v1/posts-encrypted
Accept: application/json

### get latest encrypted posts
GET http://localhost:3000/v1/posts-encrypted/latest
Accept: application/json

### get a specific encrypted post by given transaction hash value
GET http://localhost:3000/v1/posts-encrypted/1
Accept: application/json
