### get all posts
GET http://localhost:3000/v1/posts
Accept: application/json

### get latest posts
GET http://localhost:3000/v1/posts/latest
Accept: application/json

### get specific post by given transaction hash value
GET http://localhost:3000/v1/posts/1
Accept: application/json
