---
- hosts: vps
  remote_user: root
  become: true
  gather_facts: yes
  vars:
    hugin_cache_name: hugin_cache
    hugin_cache_port: 3000

    # Docker GitHub Container Registry
    docker_image: "ghcr.io/kryptokrona/hugin-cache"

    # A list of users who will be added to the docker group.
    docker_users: [
      "hugin_docker"
    ]

    docker_container_name: hugin-cache
    docker_network_name: hugin

    # Docker daemon options as a dict
    docker_daemon_options: { }

    # DO NOT CONFIGURE THE ABOVE YOURSELF

    removal_interval: '1 years 2 months 3 days 2 hours 1 minutes 1 second'
    hugin_node_server: 'blocksum.org:11898'
    index_file_url: 'https://{{ domain_name }}/api/v1/posts'
    index_file_path: 'https://raw.githubusercontent.com/TechyGuy17/Hugin-cache-homepage/master/index.html.j2'

    sys_criteria_users_include: ''
    sys_criteria_users_exclude: ''
    sys_criteria_boards_include: ''
    sys_criteria_boards_exclude: ''
    sys_criteria_keywords_include: ''
    sys_criteria_keywords_exclude: ''
    sys_criteria_keywords_cursewords: 'false'
  
  roles:
    #- base
    - postgres
    - docker
    - nginx