---
- hosts: vps
  remote_user: root
  vars:
    hugin_cache_domain: cache.hugin.chat
    hugin_cache_name: 'hugin_cache'
    hugin_cache_port: 3000
    key_out: /home/jupyter/.jupyter/jupyter.key
    cert_out: /home/jupyter/.jupyter/jupyter.cert
    postgres_db: "hugin_cache_prod"
    postgres_user: "hugin_user"
    postgres_password: "test1234"

    # Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present

    # Service options.
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted

    # Docker repo URL.
    docker_repo_url: https://download.docker.com/linux

    # Used only for Debian/Ubuntu. Switch 'stable' to 'nightly' if needed.
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_apt_ignore_key_error: true
    docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"

    # A list of users who will be added to the docker group.
    docker_users: [
      "hugin_docker"
    ]

    # Docker daemon options as a dict
    docker_daemon_options: { }

    # Docker GitHub Container Registry
    docker_image_tag: "hugin-cache:latest"
    docker_registry_url: "https://ghcr.io"
    docker_registry_user: "mjovanc"
    docker_registry_pass: ""
    docker_registry_mail: "mjovanc@protonmail.com"
  vars_prompt:
    - name: "user_name"
      prompt: "Enter a name for the new user"
      private: no
      confirm: no
    - name: "user_password"
      prompt: "Enter a password for the new user"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
  roles:
    - base
    #- express
    - nginx
    #- postgres